In [2]:
import numpy as np
import pandas as pd

In [3]:
X_train=pd.read_csv('X_train_mvh.csv')
X_test=pd.read_csv('X_test_mvh.csv')
Y_train=pd.read_csv('Y_train.csv')
Y_test=pd.read_csv('Y_test.csv')

In [4]:
X_train.head(5)

   Pclass     Sex  SibSp  Parch     Fare   Age Embarked
0       1    male      0      0  28.5000  45.5        S
1       2    male      0      0  13.0000  23.0        S
2       3    male      0      0   7.9250  32.0        S
3       3    male      1      0   7.8542  26.0        S
4       3  female      4      2  31.2750   6.0        S

In [5]:
X_train.shape

(656, 7)

In [6]:
X_train.isnull().sum()

Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Age         0
Embarked    0
dtype: int64

In [7]:
X_train['Embarked'].value_counts()

Embarked
S    478
C    120
Q     58
Name: count, dtype: int64

In [8]:
X_train['Sex'].value_counts()

Sex
male      421
female    235
Name: count, dtype: int64

In [9]:
X_train.dtypes

Pclass        int64
Sex          object
SibSp         int64
Parch         int64
Fare        float64
Age         float64
Embarked     object
dtype: object

In [10]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False)

X_train_ohe=ohe.fit_transform(X_train[['Sex','Embarked']]).astype('int64')
X_test_ohe=ohe.transform(X_test[['Sex','Embarked']]).astype('int64')

In [11]:
X_train_ohe

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       ...,
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1]])

In [12]:
X_test_ohe

array([[1, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [13]:
train_nominal_encoded_df=pd.DataFrame(X_train_ohe,columns=ohe.get_feature_names_out(),
                                        index=X_train.index)
test_nominal_encoded_df=pd.DataFrame(X_test_ohe,columns=ohe.get_feature_names_out(),
                                        index=X_test.index)
train_nominal_encoded_df

     Sex_male  Embarked_Q  Embarked_S
0           1           0           1
1           1           0           1
2           1           0           1
3           1           0           1
4           0           0           1
..        ...         ...         ...
651         0           0           1
652         1           0           1
653         1           0           1
654         0           0           1
655         1           0           1

[656 rows x 3 columns]

In [14]:
X_train=X_train.drop(columns=['Sex','Embarked']).join(train_nominal_encoded_df)
X_test=X_test.drop(columns=['Sex','Embarked']).join(train_nominal_encoded_df)

In [15]:
X_train.shape

(656, 8)

In [16]:
X_train.columns

Index(['Pclass', 'SibSp', 'Parch', 'Fare', 'Age', 'Sex_male', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [17]:
X_train.head(5)

   Pclass  SibSp  Parch     Fare   Age  Sex_male  Embarked_Q  Embarked_S
0       1      0      0  28.5000  45.5         1           0           1
1       2      0      0  13.0000  23.0         1           0           1
2       3      0      0   7.9250  32.0         1           0           1
3       3      1      0   7.8542  26.0         1           0           1
4       3      4      2  31.2750   6.0         0           0           1

In [20]:
X_train.to_csv('x_train_encoded.csv',index=False)
Y_train.to_csv('y_train_encoded.csv',index=False)
X_test.to_csv('x_test_encoded.csv',index=False)
Y_test.to_csv('y_test_encoded.csv',index=False)